#!/bin/bash
source ./cred

# Stop running program
$SSH $LOC 'kill `cat /home/pi/baja/baja.pid`'

# Sync the files over
rsync -avz -LK --delete --rsh="$SSH" ./ $LOC:/home/pi/baja/

# If args given
if [ $# -gt 0 ]; then
    echo "Building"
    $SSH $LOC "/home/pi/.arduino-1.8.5/arduino --upload --verbose-build --verbose-upload /home/pi/baja/arduino/Baja.ino"
    echo "\nBuild Finished -----------------------------"
fi

# Restart running program
$SSH $LOC "/home/pi/baja/start"